/* Core */
import { createSlice, type PayloadAction } from '@reduxjs/toolkit'
import {v4 as uuidv4} from 'uuid';

/* Instruments */
import { updateSchedules } from './thunks'

const getInitialState = (): SystemSliceState => {
  let state = {
    schedules: [],
    currentScheduleIndex: -1,
    status: 'idle',
  } as SystemSliceState

  if (typeof window !== 'undefined') {
    let scheduleString = localStorage.getItem("schedules");
    if (scheduleString) {
      state.schedules = JSON.parse(scheduleString);
    }

    let currentScheduleIndexString = localStorage.getItem("currentScheduleIndex");
    if (currentScheduleIndexString) {
      state.currentScheduleIndex = JSON.parse(currentScheduleIndexString);
    }
  }
  return state
}

export const systemSlice = createSlice({
  name: 'system',
  initialState: getInitialState(),
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    addClass: (state, action: PayloadAction<{class_number: number, schedule_id: string}>) => {
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes
      let schedule = state.schedules.find((schedule) => {schedule.id === action.payload.schedule_id});
      if (schedule) {
        schedule.class_numbers.push(action.payload.class_number)
      }
    },
    removeClass: (state, action: PayloadAction<{class_number: number, schedule_id: string}>) => {
      let schedule = state.schedules.find((schedule) => {schedule.id === action.payload.schedule_id});
      if (schedule) {
        schedule.class_numbers.filter(class_number => class_number != action.payload.class_number);
      }
    },
    // Use the PayloadAction type to declare the contents of `action.payload`
    changeCurrentSchedule: (state, action: PayloadAction<number>) => {
      if (state.schedules.length > action.payload  && action.payload > -1) {
        state.currentScheduleIndex = action.payload;
      }
    },
    createSchedule: {
      reducer(state, action: PayloadAction<{term: string, id: string, name: string}>) {
        state.schedules.push({class_numbers: [], term: action.payload.term, name: action.payload.name, id: action.payload.id})
      },
      prepare(term: string, name: string) {
        const id = uuidv4();
        return{ payload: {term: term, name: name, id: id}};
      }
    },
    deleteSchedule: (state, action: PayloadAction<string>) => {
      state.schedules = state.schedules.filter((schedule) => {schedule.id !== action.payload});
    },
    renameSchedule: (state, action: PayloadAction<{id: string, newName: string}>) => {
      let schedule = state.schedules.find((schedule) => {schedule.id === action.payload.id});
      if (schedule) {
        schedule.name = action.payload.newName;
      }
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(updateSchedules.pending, (state) => {
        state.status = 'loading'
      })
      .addCase(updateSchedules.fulfilled, (state, action) => {
        state.status = 'idle'
        state.currentScheduleIndex = Math.max(action.payload.findIndex((schedule) => {schedule.id = state.schedules[state.currentScheduleIndex].id}), Math.min(0, action.payload.length-1))
        state.schedules = action.payload;
      })
      .addCase(updateSchedules.rejected, (state) => {
        state.status = 'failed'
      })
  },
})

export const {addClass, removeClass, changeCurrentSchedule, createSchedule, deleteSchedule, renameSchedule} = systemSlice.actions

export interface Schedule {
  class_numbers: Array<number>;
  term: string;
  name: string;
  id: string;
}

/* Types */
export interface SystemSliceState {
  schedules: Array<Schedule>
  currentScheduleIndex: number
  status: 'loading' | 'failed' | 'idle'
}

export interface SystemData {
  schedules: Array<Schedule>
  currentScheduleIndex: number
}