name = "tarheel-compass"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-07-03"
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "db-tarheel-compass"
database_id = "786d9e50-3cd0-4401-8cd2-7ba56a734a74"

[env.prod.vars]
NEXTAUTH_URL="https://tarheelcompass.com"
PUBLIC_URL="https://tarheelcompass.com"

[env.preview.vars]
NEXTAUTH_URL="https://staging.tarheelcompass.com"
PUBLIC_URL="https://staging.tarheelcompass.com"

[env.preview]
name = "preview"
[[env.preview.d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "db-tarheel-compass"
database_id = "786d9e50-3cd0-4401-8cd2-7ba56a734a74"