/* Core */
import { TermData } from 'src/app/lib/Common';
import { createSlice, type PayloadAction } from '@reduxjs/toolkit'
import {v4 as uuidv4} from 'uuid';

/* Instruments */
import { updateTerms, updateUserData } from './thunks'

const getInitialState = (): SystemSliceState => {
  let state = {
    schedules: [],
    currentScheduleIndex: -1,
    status: 'idle',
    terms: undefined,
    defaultTerm: undefined
  } as SystemSliceState

  if (typeof window !== 'undefined') {
    let scheduleString = localStorage.getItem("schedules");
    if (scheduleString) {
      state.schedules = JSON.parse(scheduleString);
    }
    if (!Array.isArray(state.schedules)) {
      state.schedules = []
    }

    let currentScheduleIndexString = localStorage.getItem("currentScheduleIndex");
    if (currentScheduleIndexString) {
      state.currentScheduleIndex = JSON.parse(currentScheduleIndexString);
    } else {
      state.currentScheduleIndex = 0;
    }
  }
  return state
}

export const systemSlice = createSlice({
  name: 'system',
  initialState: getInitialState(),
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    addClass: (state, action: PayloadAction<{scheduleID: string, classNumber: number}>) => {
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes
      let schedule = state.schedules.find((schedule) => schedule.id === action.payload.scheduleID);
      if (schedule) {
        if (schedule.classNumbers.find((classNumber)=>classNumber === action.payload.classNumber) == undefined) {
          schedule.classNumbers.push(action.payload.classNumber)
        }
      }
    },
    removeClass: (state, action: PayloadAction<{scheduleID: string, classNumber: number}>) => {
      let schedule = state.schedules.find((schedule) => schedule.id === action.payload.scheduleID);
      if (schedule) {
        schedule.classNumbers = schedule.classNumbers.filter(class_number => class_number != action.payload.classNumber);
      }
    },
    // Use the PayloadAction type to declare the contents of `action.payload`
    changeCurrentSchedule: (state, action: PayloadAction<number>) => {
      if (state.schedules.length > action.payload  && action.payload > -1) {
        state.currentScheduleIndex = action.payload;
      }
    },
    createSchedule: {
      reducer(state, action: PayloadAction<{term: string, id: string, name: string}>) {
        state.schedules.push({classNumbers: [], term: action.payload.term, name: action.payload.name, id: action.payload.id})
      },
      prepare(term: string, name: string) {
        const id = uuidv4();
        return{ payload: {term: term, name: name, id: id}};
      }
    },
    deleteSchedule: (state, action: PayloadAction<{id: string}>) => {
      state.schedules = state.schedules.filter((schedule) => {schedule.id !== action.payload.id});
    },
    renameSchedule: (state, action: PayloadAction<{id: string, newName: string}>) => {
      let schedule = state.schedules.find((schedule) => {schedule.id === action.payload.id});
      if (schedule) {
        schedule.name = action.payload.newName;
      }
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(updateUserData.pending, (state) => {
        state.status = 'loading'
      })
      .addCase(updateUserData.fulfilled, (state, action) => {
        state.status = 'idle'
        if (action.payload.schedules == undefined) {
          state.currentScheduleIndex = 0;
          state.schedules = [];// so i was wondering why my schedules were being set to undefined
        } else {
          const currentSchedule = state.schedules[state.currentScheduleIndex]
          const changedIndex = (state.currentScheduleIndex >= 0 && currentSchedule != undefined) ? action.payload.schedules.findIndex((schedule) => {schedule.id = currentSchedule.id}) : -1;
          if (currentSchedule && changedIndex < 0) {
            // previously selected schedule must have been deleted elsewhere
            let targetTerm = state.defaultTerm;
            if (targetTerm === undefined) {
              if (state.currentScheduleIndex >= 0 && state.schedules.length > 0 && state.schedules[state.currentScheduleIndex]){
                targetTerm = currentSchedule.term
              }
            }
            state.currentScheduleIndex = Math.max(action.payload.schedules.findIndex((schedule) => {schedule.term == targetTerm}), Math.max(0, action.payload.schedules.length-1))
          } else {
            state.currentScheduleIndex = changedIndex;
          }
          if (Array.isArray(action.payload.schedules)) {
            state.schedules = action.payload.schedules;
            console.log("schedules changed to: ", state.schedules)
          }
        }
      })
      .addCase(updateUserData.rejected, (state) => {
        state.status = 'failed'
      })
      .addCase(updateTerms.fulfilled, (state, action) => {
        state.terms = action.payload.terms;
        state.defaultTerm = action.payload.defaultTerm
      })
  },
})

export const {addClass, removeClass, changeCurrentSchedule, createSchedule, deleteSchedule, renameSchedule} = systemSlice.actions

export interface Schedule {
  classNumbers: Array<number>;
  term: string;
  name: string;
  id: string;
}

/* Types */
export interface SystemSliceState {
  schedules: Array<Schedule>
  currentScheduleIndex: number
  status: 'loading' | 'failed' | 'idle'
  terms: Array<TermData> | undefined
  defaultTerm: string | undefined
}

export interface SystemData {
  schedules: Array<Schedule>
  currentScheduleIndex: number
}